[build]
  command = "npm run build"
  publish = "dist/public"

# API requests -> Render backend (must be before SPA fallback)
[[redirects]]
  from = "/api/*"
  to = "https://academyjakintzaruha.onrender.com/api/:splat"
  status = 200
  force = true

# Single Page App fallback so client-side routing works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: set Node version via environment (can also set in Netlify UI)
# [build.environment]
#   NODE_VERSION = "20"
